#!/usr/bin/env sh

source "$HOME/.config/colors/tokyodark.sh" # Loads all defined colors

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"

yabai -m config external_bar               all:42:0
yabai -m config window_border              on
yabai -m config mouse_follows_focus        off
yabai -m config focus_follows_mouse        off
yabai -m config window_placement           second_child
yabai -m config window_topmost             off
yabai -m config window_shadow              float
yabai -m config window_opacity             off
yabai -m config window_opacity_duration    0
yabai -m config active_window_opacity      1
yabai -m config normal_window_opacity      1
yabai -m config window_border_width        3
yabai -m config window_animation_duration  0
yabai -m config active_window_border_color $RED
yabai -m config normal_window_border_color $BLACK
yabai -m config insert_feedback_color      $ORANGE
yabai -m config split_ratio                0.50
yabai -m config auto_balance               on
yabai -m config mouse_modifier             fn
yabai -m config mouse_action1              move
yabai -m config mouse_action2              resize
yabai -m config mouse_drop_action          swap

yabai -m config top_padding                2
yabai -m config bottom_padding             2
yabai -m config left_padding               2
yabai -m config right_padding              2
yabai -m config window_gap                 6
# Do not manage some apps which are not resizable
yabai -m rule --add app="^(Calculator|VLC|System Preferences|zoom.us|Photo Booth|Archive Utility|Python)$" manage=off

# ===== Rules ==================================

yabai -m rule --add label="Hammerspoon" app="^Hammerspoon$" manage=off
yabai -m rule --add label="Steam" app="^Steam$" manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Alfred" app="^Alfred$" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="System Preferences" app="^System Preferences$" manage=off
yabai -m rule --add label="App Store" app="^App Store$" manage=off
yabai -m rule --add label="Activity Monitor" app="^Activity Monitor$" manage=off
yabai -m rule --add label="Calculator" app="^Calculator$" manage=off
yabai -m rule --add label="Dictionary" app="^Dictionary$" manage=off
yabai -m rule --add label="Software Update" title="Software Update" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add label="Select file to save to" app="^Inkscape$" title="Select file to save to" manage=off

yabai -m space 1 --label code
yabai -m space 2 --label tex
yabai -m space 3 --label web
yabai -m space 4 --label idle
yabai -m space 5 --label term

yabai -m config layout                     bsp

echo "Yabai has entered the building..."
