#!/usr/bin/env sh

ACTIVE_THEME="tokyonight" #Coresponds to global color defs in ~/.config/colors/themename.sh

source "$HOME/.config/colors/tokyonight.sh"
source "$HOME/.config/sketchybar/icons.sh" # Loads all defined icons

ITEM_DIR="$HOME/.config/sketchybar/items" # Directory where the items are configured
PLUGIN_DIR="$HOME/.config/sketchybar/plugins" # Directory where all the plugin scripts are stored

FONT="Metropolis" # Needs to have Regular, Bold, Semibold, Heavy and Black variants
ICON_FONT="Lexsa"

PADDINGS=3 # All paddings use this value (icon, label, background and bar paddings)
SEGMENT_SPACING=13 # The spacing between segments

# Set up github notifications and drop down menu
# https://github.com/FelixKratz/SketchyBar/discussions/12?sort=new#discussioncomment-2025720
# sketchybar --add       item               github.bell left                         \
#            --set       github.bell        associated_space=1                       \
#                                           update_freq=180                          \
#                                           icon.font="$ICON_FONT:Bold:30"              \
#                                           icon=G                                  \
#                                           label=$LOADING                           \
#                                           script="$PLUGIN_DIR/gitNotifications.sh" \
#                                           click_script="sketchybar --set \$NAME popup.drawing=toggle"

# Setting up the general bar appearance and default values
sketchybar --bar     height=32                                           \
                     corner_radius=0                                     \
                     border_width=0                                     \
                     margin=0                                            \
                     blur_radius=0                                       \
                     position=top                                        \
                     padding_left=4                                      \
                     padding_right=4                                     \
                     color=$BAR_COLOR                                    \
                     topmost=off                                         \
                     sticky=on                                           \
                     font_smoothing=on                                  \
                     y_offset=0                                          \
                     notch_width=0                                       \
                                                                         \
           --default drawing=on                                          \
                     updates=when_shown                                  \
                     label.font="$FONT:Regular:16.0"                     \
                     icon.font="$ICON_FONT:Regular:20"                         \
                     icon.color=$ICON_COLOR                              \
                     label.color=$LABEL_COLOR                            \
                     icon.padding_left=$PADDINGS                         \
                     icon.padding_right=$PADDINGS                        \
                     label.padding_left=$PADDINGS                        \
                     label.padding_right=$PADDINGS                       \
                     background.padding_right=$PADDINGS                  \
                     background.padding_left=$PADDINGS                   \

# Template for the segment labels, i.e. space name, active app, date, ...
sketchybar --add item           label_template left                          \
           --set label_template icon.drawing=off                             \
                                label.font="$FONT:Regular:18.0"                \
                                label.padding_right=5                        \
                                click_script="$PLUGIN_DIR/toggle_bracket.sh" \
                                background.padding_left=$SEGMENT_SPACING     \
                                drawing=off


# Spaces themselves are this
source "$ITEM_DIR/spaces.sh"

# First Seperator on the bar
sketchybar   --add item       separator left                          \
             --set separator  icon=|                                  \
                              icon.font="$ICON_FONT:Bold:30" \
                              background.padding_left=-2              \
                              background.padding_right=-7             \
                              icon.y_offset=1                         \
                              label.drawing=off                       \
                              icon.color=$RED

# BSP/float/stack/fullscreen text
 sketchybar --add       event        window_focus                      \
           --add       item         system.yabai left                 \
           --set       system.yabai script="$PLUGIN_DIR/yabai.sh"     \
                                    icon.font="$ICON_FONT:Regular:14"       \
                                    label.drawing=off                 \
                                    icon.color=$GREEN                 \
                                    icon.y_offset=1                   \
                                    icon.padding_left=8               \
                                    updates=on                        \
           --subscribe system.yabai window_focus mouse.clicked        \

# Second seperator on the bar
sketchybar   --add item       separator2 left                          \
             --set separator2  icon=                                 \
                              icon.font="$ICON_FONT:Regular:30" \
                              background.padding_right=0             \
                              background.padding_left=-3                \
                              icon.y_offset=1                   \
                              label.drawing=off                       \
                              icon.color=$YELLOW
# Space number
source "$ITEM_DIR/spacenum.sh"

# Third seperator on the bar
sketchybar   --add item       separator3 left                          \
             --set separator3  icon=|                                  \
                              icon.font="$ICON_FONT:Regular:30" \
                              background.padding_right=-5             \
                              icon.y_offset=1                   \
                              label.drawing=off                       \
                              icon.color=$WHITE                     \

# Curent procces name
sketchybar --add       event        window_focus                         \
           --add       event        title_change                         \
                                                                         \
           --add       item         window_title left                    \
           --set       window_title script="$PLUGIN_DIR/window_title.sh" \
                                    label.font="$FONT:Regular:11"               \
                                    label.y_offset=1                       \
           --subscribe window_title window_focus title_change           \

# Time Widget
sketchybar --add item clock right                                                 \
           --set clock update_freq=5                                             \
                       icon=""                                                  \
                       icon.font="$ICON_FONT:Regular:30"                      \
                       icon.padding_right=7                                          \
                       icon.color=$BLUE                                        \
                       icon.y_offset=2                                          \
                       label.y_offset=2                                          \
                       label.font="$FONT:Bold:14"                           \
                       label.color=$BLUE                                       \
                       label.padding_left=0                                       \
                       label.padding_right=8                                      \
                       background.color=$BLUE                           \
                       background.height=3                                       \
                       background.padding_right=3                                \
                       background.y_offset=-10                                       \
                       script="$PLUGIN_DIR/clock.sh"                              \
                       icon.padding_left=0 label.padding_right=1                  \

# Battery Widget
sketchybar --add item battery right                                                 \
           --set battery update_freq=10                                             \
                       icon.font="$ICON_FONT:Regular:30"                      \
                       icon.padding_right=7                                          \
                       icon.color=$YELLOW                                        \
                       icon.y_offset=2                                          \
                       label.y_offset=2                                          \
                       label.font="$FONT:Bold:14"                           \
                       label.color=$YELLOW                                       \
                       label.padding_right=8                                      \
                       background.color=$YELLOW                            \
                       background.height=3                                       \
                       background.y_offset=-10                                       \
                       background.padding_right=7                                \
                       script="$PLUGIN_DIR/battery.sh"                              \
                       icon.padding_left=0 label.padding_right=0                  \

# Updates Widget
sketchybar --add item updates right                                                 \
           --set updates update_freq=1800                                             \
                       icon=""                                                  \
                       icon.font="$ICON_FONT:Regular:23"                      \
                       icon.padding_right=7                                          \
                       icon.color=$MAGENTA         \
                       icon.y_offset=1                                          \
                       label.y_offset=2                                          \
                       label.font="$FONT:Bold:14"                           \
                       label.color=$MAGENTA \
                       label.padding_right=8                                      \
                       background.color=$MAGENTA                            \
                       background.height=3                                       \
                       background.y_offset=-10                                       \
                       background.padding_right=7                                \
                       script="$PLUGIN_DIR/package_monitor.sh"                              \
                       icon.padding_left=-1 label.padding_right=2                  \
# Uptime Widget
sketchybar --add item uptime right                                                 \
           --set uptime update_freq=50                                             \
                       icon.font="$ICON_FONT:Regular:18"                      \
                       icon.padding_right=4                                          \
                       icon.color=$GREEN                                        \
                       label.y_offset=2                                          \
                       icon.y_offset=3                                          \
                       label.font="$FONT:Bold:14"                           \
                       label.color=$GREEN                                       \
                       label.padding_right=8                                      \
                       background.color=$GREEN                            \
                       background.height=3                                       \
                       background.y_offset=-10                                       \
                       background.padding_right=7                                \
                       script="$PLUGIN_DIR/uptime.sh"                              \
                       icon.padding_left=-1 label.padding_right=2                  \

# mem Widget
sketchybar --add item  mem right                                                 \
           --set mem   update_freq=10                                             \
                       icon.font="$ICON_FONT:Regular:30"                      \
                       icon.padding_right=4                                          \
                       icon.color=$RED                                        \
                       icon.y_offset=2                                          \
                       label.y_offset=2                                         \
                       label.font="$FONT:Bold:14"                                  \
                       label.color=$RED                                   \
                       label.padding_right=8                                      \
                       background.color=$RED                           \
                       background.height=3                                       \
                       background.y_offset=-10                                       \
                       background.padding_right=7                                \
                       script="$PLUGIN_DIR/disk.sh"                              \
                       icon.padding_left=0 label.padding_right=2                  \

# If an update is avalible, update sketchybar when launched
sketchybar --update

# Finalize animations
sketchybar --animate sin 30 --bar notch_width=200

# Notify when sketchybarrc is finished loading
echo "sketchybar configuation loaded.."
